# Generated by Django 5.0.4 on 2024-05-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type_payment', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('delivery_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
